### ISSUE TITLE
BlockingCollection

### ISSUE THREAD

**Issue by avanderhoorn** [iSynaptic/MessagingShootout#1]
Did you ever consider seeing how BlockingCollection held up?

**Comment by iSynaptic** [comment]
No, I didn't because it is backed by the ConcurrentQueue to get FIFO semantics, and I already created scenarios for ConcurrentQueue.  I expected it would perform either the same or worse than ConcurrentQueue.  However, to confirm that I added two scenarios (see 86252fb3e7376ec6cd98821642c402eb7affa0ec).

**Comment by avanderhoorn** [comment]
Cool stuff!!!
